# Default Application Configuration
log:
  # Where to write logs when not in debug mode
  file: './data/app.log'
# TODO: Sqlite implementation, but for now just json
history:
  file: './data/history.json'
model:
  # Openly Available Hermes 2.5 (7B) API running on LibertAI
  name: 'OpenHermes 2.5 (7B)'
  api_url: 'https://curated.aleph.cloud/vm/a8b6d895cfe757d4bc5db9ba30675b5031fe3189a99a14f13d5210c473220caf/completion'
  engine: 'llamacpp'
  pass_credentials: true
  # TODO: should I make slot id configurable? For now it's none by default anyway.
  # slot_id: none
  max_length: 200
  max_tries: 2
  max_tokens: 16384
  temperature: 0.7
  sampler_order: [6, 0, 1, 3, 4, 2, 5]
  top_p: 0.9
  top_k: 40
  model_type: 'knowledge'
persona:
  templates:
    # Template for describing a private chat
    # {user_username} | {user_first_name} | {user_last_name} | {user_bio}
    private_chat: ./templates/private_chat.txt
    # Template for describing a group chat
    # {chat_title} | {chat_description} | {chat_members}
    group_chat: ./templates/group_chat.txt
    # TODO: maybe tools should be split out from persona
    # Template for persona prompt to the model
    # {persona_name} | {functions} | {max_functions_calls}
    # Note: in order for functions to work, you need to instruct the model within the persona prompt
    persona: ./templates/persona.txt
    # Portential reward message for the model
    # N/A (no templating)
    reward: ./templates/reward.txt
    # Potential punishment message for the model
    # N/A ( no templating)
    punishment: ./templates/punishment.txt
    # Example of a message that can be sent to the model
    # N/A (no templating)
    # Note: in order for functions to work, it is best to provide a proper example of a calling a tool, with examples of handling results, errors, and exceptions.
    example: ./templates/example.txt
chat_ml:
  user_prepend: '<|im_start|>'
  user_append: '<|im_end|>'

  stop_sequences:
    # Covers our configured bot name
    - '<|im_end|>'
    - '<|endoftext|>'
    - '</assistant'
    - '</user'
  line_separator: '\n'

# TODO: idt it's a good idea to make commands configurable, but maybe we can enable/disable them
# TODO: dyanmic tool configuration for easy integration
